"""抖音 Cookie 管理：Playwright 登录 → 导出 Netscape cookie jar，失效自动重登。"""
import os
import time
from pathlib import Path

from playwright.sync_api import sync_playwright

# 判定是否已登录的关键 cookie：必须是真实会话 cookie。
# 注意：passport_csrf_token 未登录也存在，绝不能用来判定登录态，否则会假成功。
LOGIN_COOKIE_NAMES = {'sessionid', 'sessionid_ss', 'sid_guard', 'sid_tt'}

# 让页面更像真实浏览器，降低风控概率
UA = ('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
      '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36')


def _esc(v: str) -> str:
    """Netscape 格式中需去掉会让解析错乱的字符。"""
    return v.replace('\n', '').replace('\r', '').replace('"', '')


def export_netscape(cookies, path: str) -> int:
    """把 playwright 的 cookie 列表写成 Netscape 格式（yt-dlp --cookies 兼容）。"""
    lines = [
        '# Netscape HTTP Cookie File',
        '# generated by douyin-pipeline. do not edit.',
    ]
    for c in cookies:
        domain = c.get('domain', '')
        if not domain:
            continue
        # Netscape 格式：仅当前面带点(.)的域名才允许 TRUE(包含子域)，否则解析器断言失败
        include_sub = 'TRUE' if domain.startswith('.') else 'FALSE'
        p = c.get('path', '/') or '/'
        secure = 'TRUE' if c.get('secure') else 'FALSE'
        expires = int(c.get('expires', 0) or 0)
        name = _esc(c.get('name', ''))
        value = _esc(c.get('value', ''))
        lines.append(f"{domain}\t{include_sub}\t{p}\t{secure}\t{expires}\t{name}\t{value}")
    Path(path).write_text('\n'.join(lines) + '\n', encoding='utf-8')
    return len(cookies)


def load_netscape_names(path: str) -> set:
    """读取 cookie jar 中所有 cookie 名，用于判断登录态。"""
    names = set()
    if not os.path.exists(path):
        return names
    for line in Path(path).read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        parts = line.split('\t')
        if len(parts) >= 7:
            names.add(parts[5])
    return names


def has_login(names: set) -> bool:
    return bool(names & LOGIN_COOKIE_NAMES)


def login_and_export(cookies_file: str, timeout_sec: int = 300) -> bool:
    """打开有头浏览器到抖音，等待用户扫码登录，然后导出 cookie。"""
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        ctx = browser.new_context(locale='zh-CN', user_agent=UA)
        page = ctx.new_page()
        page.goto('https://www.douyin.com/', wait_until='domcontentloaded')
        print('请在打开的浏览器中扫码登录抖音（超时自动保存当前 cookie）…')
        deadline = time.time() + timeout_sec
        logged = False
        while time.time() < deadline:
            time.sleep(2)
            if has_login({c.get('name') for c in ctx.cookies()}):
                logged = True
                break
        cookies = ctx.cookies()
        n = export_netscape(cookies, cookies_file)
        print(f'已导出 {n} 条 cookie 到 {cookies_file}，登录态: {logged}')
        browser.close()
        return logged


def ensure_cookies(cookies_file: str, force: bool = False) -> bool:
    """保证存在有效登录 cookie；缺失/失效则自动重新登录。"""
    if not force and os.path.exists(cookies_file):
        names = load_netscape_names(cookies_file)
        if has_login(names):
            print(f'cookies 已存在且含登录态: {cookies_file}')
            return True
        print('cookies 无有效登录态，触发重新登录…')
    return login_and_export(cookies_file)
